module.exports = {
  admin: require('./admin')
  auth: require('./auth')
  apcsp: require('./apcsp')
  analyticsLogEvents: require('./analytics-log-events')
  campaigns: require('./campaigns')
  classrooms: require('./classrooms')
  courses: require('./courses')
  courseInstances: require('./course-instances')
  levels: require('./levels')
  levelSessions: require('./level-sessions')
  markdown: require('./markdown')
  prepaids: require('./prepaids')
  skippedContacts: require('./skipped-contacts')
  thangTypes: require('./thang-types')
  trialRequests: require('./trial-requests')
  userCodeProblems: require('./user-code-problems')
  users: require('./users')
}
