; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Code Combat Developers Environment"
#define MyAppPublisher "Code Combat"              
#define MyAppVersion "1.0"
#define MyAppURL "http://www.codecombat.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{91BF8350-EFB7-4B49-A6F3-18AF88F0E2EC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\CodeCombat
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\LICENSE.txt
InfoAfterFile=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\README.txt
OutputDir=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\bin
OutputBaseFilename=codo-dev-setup
SetupIconFile=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\logo.ico
Compression=lzma
SolidCompression=yes 
ShowLanguageDialog=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"  

#include ReadReg(HKEY_LOCAL_MACHINE,'Software\Sherlock Software\InnoTools\Downloader','ScriptPath','');

[Code]
procedure InitializeWizard();
begin
 itd_init;

 //Let's download two zipfiles from my website..
 itd_addfile('http://www.sherlocksoftware.org/petz/files/dogz5.zip',expandconstant('{tmp}\dogz5.zip'));
 itd_addfile('http://www.sherlocksoftware.org/petz/files/petz4.zip',expandconstant('{tmp}\petz4.zip'));

 //Start the download after the "Ready to install" screen is shown
 itd_downloadafter(wpReady);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
 if CurStep=ssInstall then begin //Lets install those files that were downloaded for us
  filecopy(expandconstant('{tmp}\dogz5.zip'),expandconstant('{app}\dogz5.zip'),false);
  filecopy(expandconstant('{tmp}\petz4.zip'),expandconstant('{app}\petz4.zip'),false);
 end;
end;