; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Code Combat Developers Environment"
#define MyAppPublisher "Code Combat"              
#define MyAppVersion "1.0"
#define MyAppURL "http://www.codecombat.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{91BF8350-EFB7-4B49-A6F3-18AF88F0E2EC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\CodeCombat
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\LICENSE.txt
InfoAfterFile=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\README.txt
OutputDir=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\bin
OutputBaseFilename=codo-dev-setup
SetupIconFile=E:\GameDevelopment\opensource\codecombat\scripts\windows\coco-dev-setup\installer\logo.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

