module.exports =
  auth: require './auth'
  classrooms: require './classrooms'
  campaigns: require './campaigns'
  courseInstances: require './course-instances'
  files: require './files'
  named: require './named'
  patchable: require './patchable'
  rest: require './rest'
  trialRequests: require './trial-requests'
  users: require './users'
  versions: require './versions'
