const { codeToBlocks } = require('lib/code-to-blocks')

describe('codeToBlocks Integrity & Regression Suite', () => {
  let minimalMockPrepData

  beforeEach(() => {
    minimalMockPrepData = {
      RobIsAwesome: true,
      plan: [
        [{ type: 'math_number' }, { type: 'NumericLiteral' }],
        [{ type: 'logic_compare' }, { type: 'BinaryExpression' }],
        [{ type: 'controls_if' }, { type: 'IfStatement' }],
        [{ type: 'variables_set' }, { type: 'VariableDeclaration' }],
      ],
    }
  })

  function findBlocksByType (blockContainer, targetType) {
    const foundBlocks = []
    if (!blockContainer || !blockContainer.blocks) return foundBlocks

    function walk (block) {
      if (!block) return
      if (block.type === targetType) {
        foundBlocks.push(block)
      }
      // Follow the nextify statement chains (.next.block)
      if (block.next && block.next.block) {
        walk(block.next.block)
      }
      // Follow internal value inputs slots
      if (block.inputs) {
        for (const key in block.inputs) {
          if (block.inputs[key].block) {
            walk(block.inputs[key].block)
          }
        }
      }
    }

    // Scan all root array entries generated by nextify
    blockContainer.blocks.forEach(rootBlock => walk(rootBlock))
    return foundBlocks
  }

  it('should safely wrap standalone trailing identifiers in expression_statements', () => {
    const code = `
if 1 < 2:
    typeRight = 2
typeRight
    `.trim()

    const result = codeToBlocks({
      code,
      originalCode: '',
      codeLanguage: 'python',
      prepData: minimalMockPrepData,
    })

    const expressionStatements = findBlocksByType(result.blocks, 'expression_statement')

    // we should generate a expression for the typeRight to avoid no previous error
    expect(expressionStatements.length).toEqual(1)
    const wrappedBlock = expressionStatements[0]
    expect(wrappedBlock.inputs.EXPRESSION.block.type).toEqual('variables_get')
    expect(wrappedBlock.inputs.EXPRESSION.block.fields.VAR.id).toEqual('typeRight')
  })

  it('should NOT wrap identifiers when they are evaluated inside expression statement terms', () => {
    // Here, typeRight is an expression term inside the condition, NOT a standalone statement line.
    const code = `
typeRight = 2
if typeRight < 1:
    typeRight = 5
    `.trim()

    const result = codeToBlocks({
      code,
      originalCode: '',
      codeLanguage: 'python',
      prepData: minimalMockPrepData,
    })

    const expressionStatements = findBlocksByType(result.blocks, 'expression_statement')
    // when variable use normally, we don't touch expression statement at all
    expect(expressionStatements.length).toEqual(0)
    // instead still following old variables_get logic
    const variableGetBlocks = findBlocksByType(result.blocks, 'variables_get')
    expect(variableGetBlocks.length).toBeGreaterThan(0)
    expect(variableGetBlocks[0].fields.VAR.id).toEqual('typeRight')
  })
})