name: ESLint CI

# Triggering workflow on all push
on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: 18.10.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # OR: yarn

      - name: Fetch the base branch, so we can use `git diff`
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Fetch the master branch, so we can use `git diff`
        run: git fetch origin master:master

      - name: Run eslint on changed files
        run: npm run ci-lint
