name: ESLint CI

# Triggering workflow on all push
on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: 18.10.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # OR: yarn

      - name: Run eslint on changed files
        run: npm run ci-lint

      - name: Test eslint setup works on CI
        run: cat .eslintrc.js && npm run lint --verbose
